### ISSUE TITLE
Choppy video with DoorBird D11x

### ISSUE THREAD

**Issue by axelbrunger** [hjdhjd/homebridge-doorbird#181]
I still get choppy live video with the DoorBird D11x. I recall that this was mentioned in previous posts. Is there an update? In the meantime is it possible to tweak the ffmpeg options to prevent this issue? Thank you.

**Comment by hjdhjd** [comment]
In short: nope. 

If you want faster video, disable audio. The issues are endemic to Doorbird. If you have a better ffmpeg magic incantation, feel free to share it and we’ll test and see.

**Comment by tobiswelten** [comment]
Hey,

my issue is gone since I installed version 130  on my D11x which got released last Friday. I now have a stable stream and no issues in low light situations any more.

**Comment by axelbrunger** [comment]
I also have version 130 on my D11x, but the video is choppy during daylight as well as at night.  It is fine when I view it through the DoorBird app or on a web browser via HTML.

**Comment by tobiswelten** [comment]
hmm...I would lie if there is not a choppy pixel here and there but the stream is fine for me as well. Since my setup is not capable of connecting to RTSP stream directly I have to transcode it to MJPG with MotionEye and eventually that can cause "my" choppy pixel. I don't know. I also requesting the RTSP stream with just 5fps and not with 12fps like the documentation is saying.

**Comment by axelbrunger** [comment]
How did you set the RTSP stream to 5 fps within the DoorBird plugin settings?

**Comment by tobiswelten** [comment]
> How did you set the RTSP stream to 5 fps within the DoorBird plugin settings? 
 I added some Ffmpeg options like this:

"ffmpegOptions": "-r 5 -prob....


![image](https://user-images.githubusercontent.com/45980402/104956679-e976a780-59cc-11eb-8efc-008331654b1b.jpeg)

**Comment by axelbrunger** [comment]
Thank you. Using the "-r 5 ..." option  seems to help a just a little bit but the video still stalls after a few seconds and in the Homebridge log file it still says:

[1/18/2021, 12:21:05 PM] [Doorbird] Doorbird: HomeKit video stream requested: 1920x1080, 30 fps, 802 kbps.

How can one reduce the requested frame rate?

**Comment by hjdhjd** [comment]
You can't. HomeKit requests whatever frame rate it wants. The plugin, and homebridge, has no real control over that.

**Comment by axelbrunger** [comment]
Still having problems with this. Is it possible to request a http stream rather than the rtsp stream within the ffmpeg options in the Doorbird plugin?

**Comment by axelbrunger** [comment]
As follow-up http://<it-address>/bha-api/video.cgi works great for me and there is no delay in starting the video either. Is it possible to use this http call rather than the RTSP call within the doorbird plugin?

**Comment by hjdhjd** [comment]
No. The issue is audio sync. To get true audio / video sync, you need the RTSP stream. The MJPG stream is decent for video-only. If you try to mux (combine) the audio and MJPG stream the audio sync is noticeably terrible. The issue is at the source, ultimately, not this plugin. I'll be pushing a release when I have a bit of time that should improve things, particularly for newer devices.
