### ISSUE TITLE
No rich notifications

### ISSUE THREAD

**Issue by TangoTaker** [hjdhjd/homebridge-doorbird#31]
I receive normal push notifications on motion sensor activity from homekit but no fancy rich notifications with the camera picture. Any help would be appreciated.

**Comment by brownad** [comment]
Check how you wired up doorbird to the plugin

Best way is to test the doorbell endpoint directly:

Http://whateverhomebridgeis:5005/doorbell.html

This will fire off the notifications if you have enabled it in home app

Look at the configuration section again you have to register the homebridge to doorbird (do this in a browser if you want) then in the app you’ll see if its registered correctly.

**Comment by TangoTaker** [comment]
When I do that i get a Homekit message that the doorbell rang but its no rich notification, it does not include a picture in the message. What do you mean by registering the homebridge to doorbird?
Thanks in advance

**Comment by brownad** [comment]
Ah ok that’s good did you add the correct url for your doorbird image in the config? 

Make sure that resolves in a browser as a small test.

I thought you said you only have motion working and not doorbell, if you don’t then look at the configuration section in the readme, you have to register your homebridge endpoints to doorbird so that doorbird can tell the plugin about the events.

If you’ve done this and are receiving just a notification on ring without the image suggest checking your snapshot url first

**Comment by TangoTaker** [comment]
Both the snapshot url and the normal stream work fine, I can just open them in a browser. The Snapshot url:

"stillImageSource": "-i http://httpuser=XXX&http-password=XXX@192.XXX.XXX.223/bha-api/image.cgi"

What else could be the problem?

**Comment by brownad** [comment]
That is odd - I’ve seen it randomly but it’s not down to anything I have.

Try rebooting homebridge again, do you push to other devices and have external access to via Apple TV / ipad?

**Comment by brownad** [comment]
@TangoTaker still facing this issue?

**Comment by TangoTaker** [comment]
No, thanks. My Doorbird sensor doesnt work so i replaced it with s hue sensor and now I get rich notifications.
