### ISSUE TITLE
LockMechanism

### ISSUE THREAD

**Issue by unaxboy** [hjdhjd/homebridge-doorbird#5]
Hi, thanks for great plugin!

I have one idea how to enhance your plugin. If you will use LockMechanism service instead of OpenDoor it will show notification with Unlock button.

**Comment by brownad** [comment]
Sure I will look into it

**Comment by unaxboy** [comment]
Hi, did you already try?)

**Comment by brownad** [comment]
Nope. Not yet I had done it before but needed to change a few things, you're welcome to make a pull request if you want to..

**Comment by hjdhjd** [comment]
Will be interesting to see how it comes together...that would make for an almost complete solution as far as HomeKit-enabling Doorbird. The only thing left would be to be able to trigger the infrared light through HomeKit. Minor, but would feel satisfying to have a complete solution. :)

Is there an ETA on leveraging LockMechanism out of curiosity?

**Comment by unaxboy** [comment]
You can. Where is DoorBird Light accessory. If you put with LockMechanism accessory, then you'll have Light button besides Unlock.

**Comment by brownad** [comment]
The infrared light is a bit novel - found it better to come on automatically at night time done within the app itself and saved there.  But as you said pair it in the room and it will come up.

I am looking at the lock mechanism I'll post back here when done coming with some other changes needed.

I really want to bring in the video feed too and move to a proper video doorbell so preparing for that also

**Comment by brownad** [comment]
First attempt with LockMechanism, some things I'd like to improve on e.g. reseting state, needs more polish but have a look if you want.

Notice the config.json changed, to move away from Doorbell and over to DoorBird naming @unaxboy  @hjdhjd

**Comment by brownad** [comment]
reverted to Doorbell caused pain,,,

**Comment by brownad** [comment]
To clean remove previous one

sudo npm uninstall homebridge-doorbird

Delete the file from /homebridge/accessories

**Comment by brownad** [comment]
Last commits are done. closing this out.

Hope its what you wanted :)

**Comment by unaxboy** [comment]
Thanks again for great work!) I'll check it out when come back from vacation)

**Comment by brownad** [comment]
Enjoy 🤙

**Comment by hjdhjd** [comment]
Nice update. So, the lock / unlock feature works well. As does the (infrared) light on / off.

HOWEVER...ringing the doorbell doesn't fire an event now as it should. Thoughts?

**Comment by brownad** [comment]
Check the hack people have had to implement on motion sensor, out of my control since motion sensor starts to unregister itself
https://github.com/brownad/homebridge-doorbird/issues/4

Ideally I spend some time implementing the camera to the plugin then it's simply swapping out the motion sensor with a doorbell accessory. Just need time 🙃

**Comment by brownad** [comment]
You should see the doorbell event in the logs it does get called else there's something going on

**Comment by hjdhjd** [comment]
Not seeing it. Actually, as I look at it more closely, It isn't firing motion events or doorbell events now.

**Comment by brownad** [comment]
That's odd I'll take a look at it, the only other problem according to doorbird is the stream is too aggressive which they're going to change in the api 

If you restart you should see it start again. I've noticed without the hack I end up with no events after a day.

Either way I'll look into it

**Comment by brownad** [comment]
The other way to test is whether the api responds directly in other words subscribe to the same api in a browser you will see the updates directly.

I think there's some magic in the client api as other devices that are more official don't see the updates all the time 😕

**Comment by hjdhjd** [comment]
I'll test it over the weekend. The thing is...the prior major version of this plugin worked perfectly. Not sure if something minor may have changed in the code update.

**Comment by hjdhjd** [comment]
I've gotten the camera working fine with the ffmpeg-camera-ffmpeg. Works like a charm. I've added the working Doorbird camera config to their wiki at:

https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki/Tested-Configuration#doorbird-video-doorbell---full

Not sure it's worth implementing the camera separately in this plugin...I can see it both ways.

If I could have the doorbell event fire reliably, I'd be set. Personally...I don't find the motion event useful for my use case, and I'd disable it...but it doesn't bother me. :)

**Comment by brownad** [comment]
Didn't touch the other parts but I'll look at the diffs 

Some cleanup was done but tested each piece before committing

**Comment by brownad** [comment]
what I want to do is bring the camera in and then it's a video doorbell without needing a separate plugin e.g. Ffmpeg, adding a doorbell service to the camera instantly removes the motion sensor doorbell and yes I would prefer to drop the motion sensor it's kinda pointless but respects the features.  I might make it optional in the config for starters...

**Comment by brownad** [comment]
you could try to reboot doorbird, and homebridge 

see if that helps

**Comment by hjdhjd** [comment]
Rebooted all around...motion seems to be working again. Doorbell, will test again tomorrow.

Agree on the motion...in an earlier version, you made the events that were listened to configurable, which was nice...I had set it to just listen to the doorbell. I wonder if that's part of the challenge...so many events get triggered by the motion event. The Doorbird is very sensitive when it comes to the motion sensor. If you live in a high-traffic area, you're basically watching it get triggered every couple of minutes.

As to the camera...I get your point, and I agree it's nice to have a self-contained one-stop-shop for Doorbird. In my case, I have IP cameras as well, so I'm using both plugins anyway.

Now...if we can get that doorbell working reliably...

**Comment by brownad** [comment]
That's good news

The motion sensor is only useful if you add extra automation around it I wouldn't use it for notifications it's just annoying

**Comment by hjdhjd** [comment]
Agree on the motion sensor data point. Generally though...it really needs a sensitivity setting, not just a mask setting. I got the doorbell working today, WITH unlock from the smart notification. Works like a charm...the concern I have is that it seems flaky / fragile.

Given that some others have had challenges with the reliability of responding to events...two suggestions:

1. Implement a way to limit which events I subscribe to (mentioned above...don't need motion, which fires much more often than the doorbell event). The idea being that it would reduce whatever flakiness the Doorbird API may have.

2. Use a different API to check for events. The notification request API seems like a good option here:

http://<deviceip>/bha- api/notification.cgi?url=http://foo.bar?doorbell&user=&password=&event=doo rbell&subscribe=1

Allows you to have the Doorbird call a URL when an event fires rather than monitoring a continuous stream. Just a guess that this may be more robust...of course, you have to implement an HTTP service then...believe the ffmpeg plugin does this to stream video, but don't quote me on it.  On the plus side, it would eliminate the need for a constant connection to the Doorbird and reduce potential resource contention weirdness with the official app. You should probably have code in there to check the state of current subscriptions and clean them up if needed as well, just to be extra safe / sane...

What do you think?

**Comment by brownad** [comment]
All great ideas but a motion sensor is what it is, it fires off when there's motion unless there is a sensitivity setting in HomeKit I'm not invested in creating it, you can have a go and make a PR if you want

I think it's not worth the time it does almost the same as it does in the app and is about as useful as what the motion sensor does in the app...

The notification API is quite slow and also didn't work every time.. also needs more work than it looks.

**Comment by brownad** [comment]
Have you tried adjusting the sensitivity of the motion sensor in the app first, it might affect the api.

What I have added was a wait around the motion sensor updates so that it delayed the event to the app a few seconds thus ignoring casual movements but increasing it meant you we'd soon of sync with what's happening.

**Comment by brownad** [comment]
I see the problem - DoorBird updated firmware to "FIRMWARE": "000105","BUILD_NUMBER": "45307"

Check your info.cgi? request.  This has broken the api, for both mine and a more official one e.g. Zipatile.  I'll mention it to them

**Comment by hjdhjd** [comment]
You're spot on:

{"BHA": { "RETURNCODE": "1", "VERSION": [{"FIRMWARE": "000105","BUILD_NUMBER": "45307",

Any ETA from Doorbird on fixing this, or a way to work around it?

**Comment by brownad** [comment]
It's a holiday in Germany waiting to here back but maybe you can confirm if you do the check and ring URL in a browser seems nothing is coming back before you at least had a response and a value but I might be wrong. Image and streaming and the light and lock are all fine events somewhat painful

Coincidence as this was rolled out recently ...

**Comment by brownad** [comment]
No response yet, however, I can see the update on the firmware is now more defensive if you have more than 1 client connecting to the stream endpoint.  I show a small message in the logs now if you hit this on load.  It probably needs more work to defend against the stream going offline etc.  But this changes how it would have worked if you have other devices consuming the API - which I did, it took them all out
